### ISSUE TITLE
Rewrite download code

### ISSUE THREAD

**Issue by hkarl** [hkarl/mw2pdf#1]
Currently, separate login process for each download. 

Rewrite to extract the Site object, login to that, and pass it around. Should speed up downloads quite abit and reduce load on wiki server.

**Comment by mpeuster** [comment]
If we extract this, it would make sense to rename the wikiFetcher.py into mwiki.py and also move the

`def uploadDocument(doc, excp):`

function to it. So, everything dealing with the remote wiki is encapsulated in this module and uses one connection object.
