### ISSUE TITLE
Spell checker integration

### ISSUE THREAD

**Issue by mpeuster** [hkarl/mw2pdf#6]
During the review meeting an issue with one of the deliverables came up: It has lots of typos!

To prevent such problems in the feature, we might integrate a spell checker in the PDF generator.

Pedro already provided a link to this nice library: https://github.com/blatinier/pyhunspell

The idea would be:
- check spelling during PDF generation
- mark words with wrong spelling (RED / red line)
- add field to document options (spell_check: On / Off)

Optional ideas:
- add a watermark to documents which were generated with activated spell checking (to prevent accidental submission of these drafts)
- add a wikipage "Dictionary" to which everybody can add words that should be in the spell checker dictionary

**Comment by paaguti** [comment]
Maybe include there selection of the base dictionary (e.g. en-GB vs. en-US)

**Comment by mpeuster** [comment]
Played around with spell checking. Learned that its not as trivial as I thought ;-)
1. Working on the Latex files isn't possible. They are too complex and you destroy them if you let the spell checker apply changes to highlight mistakes.
2. Directly manipulating PDFs is no fun.
3. Marking mistakes in the *.md files is still tricky. Using format changes like `<strike>` break Latex because spelling mistakes might occur everywhere, e.g., in section headings. Using ??word?? to mark mistakes seems to be reasonable safe!

Commit b4e9a49d5b25d804843db1cfad9b99001bc507d5 provides a first working version without much features.

Use: run build.py with `--spellcheck` to enable it.

All mistakes are marked like: ??bad-word?? in the output PDF.

Note: Its not activated on the production system yet.
